import React from "react";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { Card, CardContent } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import { Pie } from "react-chartjs-2";
import "tailwindcss/tailwind.css";

const KPI_PIE_COLORS = ["#6366F1", "#10B981", "#F59E0B", "#EF4444", "#3B82F6", "#8B5CF6"];

const kpis = [
  {
    title: "Active Clients / Pilots Launched",
    desc: "Tracks the number of products launched with real clients.",
    example: "e.g. 4 pilots launched in petrochemical sector",
    progress: 4,
    target: 16,
    color: KPI_PIE_COLORS[0]
  },
  {
    title: "Revenue Generated",
    desc: "Cumulative revenue generated by launched projects.",
    example: "e.g. $150K generated out of $600K goal",
    progress: 150,
    target: 600,
    color: KPI_PIE_COLORS[1]
  },
  {
    title: "Venture Proposals Incubated",
    desc: "Number of venture proposals actively under development.",
    example: "e.g. 60 proposals actively incubated",
    progress: 60,
    target: 240,
    color: KPI_PIE_COLORS[2]
  },
  {
    title: "Growth of Strategy Team",
    desc: "Tracks team size and strategic capacity over time.",
    example: "e.g. 3 members currently hired",
    progress: 3,
    target: 6,
    color: KPI_PIE_COLORS[3]
  },
  {
    title: "Client Feedback & Partnerships",
    desc: "Measures partnerships and quality of client relationships.",
    example: "e.g. 5 active partnerships, 4.2/5 avg rating",
    progress: 5,
    target: 20,
    color: KPI_PIE_COLORS[4]
  },
  {
    title: "Employee Skill Directory Progress",
    desc: "Tracks internal skills/resume mapping completion.",
    example: "e.g. 25 profiles out of 100 completed",
    progress: 25,
    target: 100,
    color: KPI_PIE_COLORS[5]
  }
];

function KPIChart({ kpi }) {
  const data = {
    labels: ["Progress", "Remaining"],
    datasets: [
      {
        data: [kpi.progress, Math.max(kpi.target - kpi.progress, 0)],
        backgroundColor: [kpi.color, "#E5E7EB"]
      }
    ]
  };

  return (
    <div className="bg-white rounded-2xl shadow-md p-4 m-2 w-full md:w-1/2 lg:w-1/3">
      <h2 className="text-xl font-semibold text-gray-800 mb-1">{kpi.title}</h2>
      <p className="text-sm text-gray-600 italic mb-1">{kpi.desc}</p>
      <p className="text-sm text-gray-500 mb-2">{kpi.example}</p>
      <Pie data={data} />
    </div>
  );
}

function DangerZone() {
  const dangerKpis = kpis.filter(k => k.progress / k.target < 0.3);
  return (
    <div className="bg-red-100 rounded-xl p-4 mt-8">
      <h3 className="text-lg font-bold text-red-700 mb-2">🚨 Danger Zone</h3>
      <ul className="list-disc pl-5">
        {dangerKpis.map((k, i) => (
          <li key={i} className="text-red-800 font-medium">{k.title}: {((k.progress / k.target) * 100).toFixed(0)}%</li>
        ))}
      </ul>
      <Separator className="my-4" />
      <p className="text-sm text-gray-800 font-medium">Suggested Academic Solutions:</p>
      <ul className="list-disc pl-5 text-sm text-gray-700">
        <li>
          Grant, R. M. (1996). Toward a knowledge-based theory of the firm. *Strategic Management Journal*, 17(S2), 109–122.
        </li>
        <li>
          Teece, D. J. (2007). Explicating dynamic capabilities: the nature and microfoundations of (sustainable) enterprise performance. *Strategic Management Journal*, 28(13), 1319–1350.
        </li>
      </ul>
    </div>
  );
}

export default function AIVSDashboard() {
  return (
    <div className="p-6 bg-gray-50 min-h-screen">
      <header className="text-center mb-8">
        <img src="/logo.png" alt="AIVS Logo" className="mx-auto h-16" />
        <h1 className="text-3xl font-bold text-gray-800">AIVS Co. Strategic Dashboard</h1>
        <p className="text-gray-600 mt-1">Prepared by: Strategic Advisor (Saleh Zareei)</p>
      </header>

      <Tabs defaultValue="overview" className="w-full">
        <TabsList className="mb-4 justify-center gap-4">
          <TabsTrigger value="overview">Executive Summary & KPIs</TabsTrigger>
          <TabsTrigger value="phase1">Phase 1: Foundation</TabsTrigger>
          <TabsTrigger value="phase2">Phase 2: Market Penetration</TabsTrigger>
          <TabsTrigger value="phase3">Phase 3: Scaling</TabsTrigger>
        </TabsList>

        <TabsContent value="overview">
          <section className="mb-6">
            <h2 className="text-2xl font-semibold text-gray-700 mb-2">Executive Summary</h2>
            <p className="text-gray-600 leading-relaxed">
              AIVS Co. is rich in innovation but requires structured market pathways. This roadmap aligns innovation with real-world traction, starting in Iran and scaling globally.
            </p>
          </section>

          <Separator className="my-6" />

          <section className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {kpis.map((k, i) => (
              <KPIChart key={i} kpi={k} />
            ))}
          </section>

          <DangerZone />
        </TabsContent>

        <TabsContent value="phase1">
          <PhaseContent phase="Phase 1: Foundation" />
        </TabsContent>

        <TabsContent value="phase2">
          <PhaseContent phase="Phase 2: Market Penetration" />
        </TabsContent>

        <TabsContent value="phase3">
          <PhaseContent phase="Phase 3: Scaling" />
        </TabsContent>
      </Tabs>
    </div>
  );
}

function PhaseContent({ phase }) {
  return (
    <div className="bg-white p-6 rounded-xl shadow-md">
      <h2 className="text-2xl font-bold text-gray-700 mb-2">{phase}</h2>
      <p className="text-gray-600">Details and KPIs for this phase will appear here.</p>
      <DangerZone />
    </div>
  );
}
